#!/usr/bin/env python3
# -*- coding: utf-8 -*-
"""
Created on Wed Sep 13 13:10:37 2023

@author: marco
"""

import pandas as pd 

df = pd.read_csv('resto_sales.csv')

#loading the .csv file we see that the file has 5 columns and 4655 rows pertaining to restaurant sales, but let's explore the data a bit more 

#%% DATA EXPLORATION

df.head(5) #this line gives us a look at the first 5 rows of the dataframe 
df.info() #this line gives us an overview of the number of columns, their labels, rows that are non-null, as well as the data types of each column 
df.describe() #this line gives us an overview of the order_id and quantity column, since these two columns have integers within them 

#now that we have an initial exploration of the data, we can proceed to clean the data for better analysis

#%% DATA CLEANING  

#keeping in mind the informatin seen in the df.info line above, we can see that through the 4622 rows within the df, 
#there are 1,246 rows that are empty within the choice_descriptin column. Let's validate this.

df['choice_description'].isnull().sum() #running this line validates that there are indeed 1,246 rows within the choice_description column that are empty. For the purpose of this exercise, let's delete them 

df = df.dropna() #this line drops the rows with null values, and moverwrites the initial dataframe we loaded. 

df['item_price'] = df['item_price'].replace('[\$,]', '', regex=True).astype(float) #remove $ sign from item_price column, and convert numbers into float so that we can add the numbers 

df.to_excel(r'/Users/marco/Desktop/resto_sales.xlsx', index=False) #for tableau 

#%% QUICK CHECK & ANALYSIS GOALS

#So we now have a df that has 3376 rows and 5 columns, containing the following information:
    #order_id 
    #quantity 
    #item_name 
    #choice_description
    #item_price 
    
#For the sake of this restaurant sales analysis, let's check the data for the following information:
    # Total revenue generated 
    # Average order value 
    # The number of unique items sold 
    # Top 5 most popular items sold based on quantity 
    # Top 5 revenue-generating items based on price 

#%% ANALYSIS 

#Let's now address the points of analysis that we outlined above 

# Total Revenue Generated 

df.item_price.sum() # $30,422.22 revenue generated 

# Average order value 

order_totals = df.groupby('order_id')['quantity', 'item_price'].sum() # Group by 'order_id' and calculate the total value of each order

order_totals['aov'] = order_totals['item_price'] / order_totals['quantity'] # Calculate the average order value (aov) into a new column 

# The number of unique items sold 
df.item_name.nunique() #38 unique items (keep in mind we deleted rows that we're null, if we kept them we would see 50 unique items)

# Top 5 most popular items sold based on quantity
pop_items = df.groupby('item_name')['quantity'].sum().reset_index().sort_values(by='quantity', ascending=False).head(5) 
#in this line, we group by item_name, sum the quantities sold per item, and sort the values in descending order and take the top 5 

# Top 5 revenue generating items based on price
rev_items = df.groupby('item_name')['item_price'].sum().reset_index().sort_values(by='item_price', ascending=False).head(5)
#in this line, we group by item_name, sum the total revenue per item, and sort the values in descending order and take the top 5 

#%% DATA VISUALIZATION

from plotnine import *

# A Bar Plot showcasing the top 5 most popular items based on quantity 
ggplot(pop_items, aes(x='item_name', y='quantity')) + geom_bar(stat='identity')


# A Bar Plot showcasing the top 5 most popular items based on revenue 
ggplot(rev_items, aes(x='item_name', y='item_price')) + geom_bar(stat='identity')

#%% SUMMARY 

#In this simple exercise, we were able to gain the following insights: 
    #1. The total revenue generated by the restaurant in this data set is around $30.4K 
    #2. The aov per order 
    #3. There are 38 unique items sold (keeping in mind the removal of rows with null values)
    #4. The top 5 most popular items based on quantity are: 
        #Chicken Bowl, Chicken Burrito, Steak Burrito, Canned Soft Drink and Steak Bowls 
    #5. The top 5 most popular items based on revenue are: 
        #Chicken Bowl, Chicken Burritos, Steak Burrito, Steak bowl and Chicken Salad Bowl 
    #6. Data Visualization for #4 & #5 

